title: "[Q&A]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Ask the Community

        Have a question about using JudgeAI? Ask here!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: "How do I..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any additional context that might help others answer your question
